### ISSUE TITLE
Problem running `pnpm anvil`

### ISSUE THREAD

**Issue by hara-desu** [Cyfrin/ts-nft-marketplace-cu#3]
Hello!

I have a problem during the setup stage. 

When I try to run ```pnpm anvil``` I get an error: "error: invalid value 'marketplace-anvil.json' for '--load-state <PATH>': failed to parse json file: "marketplace-anvil.json": missing field `index` at line 1252 column 29". 

I think that something may be wrong with marketplace-anvil.json file.

How can I fix this except for doing ```anvil --dump-state```? 

Thank you.

**Comment by PatrickAlphaC** [comment]
Ah yes! This is likely due to an anvil mis-match. What version of anvil are you using? If you update to latest it should work now

**Comment by hara-desu** [comment]
Hello, Patrick!

Thank you for the answer :)

I have reinstalled foundry and now have anvil 1.4.4 installed which was released 3 weeks ago according to foundry's github repo.

But I still get the same error... Perhaps, I need to downgrade foundry **but to which version**? 
(I've tried to downgrade to 1.4.2 but I get the same error)
Maybe the new foundry release is incompatible with the ```marketplace-anvil.json``` file in the tutorial? 

Thank you and have a wonderful Devconnect ^^

**Comment by hara-desu** [comment]
Hello, Patrick!

Thank you for the answer :)

I have reinstalled foundry to version 1.4.4 which was released 3 weeks ago according to foundry's github repo. But I still got the same error... The new 2025 foundry releases are incompatible with the marketplace-anvil.json file in the tutorial.

I have downgraded to version 1.3.6 and now it works.

Thank you and have a wonderful Devconnect ^^
